# Generated by Django 4.2.1 on 2023-05-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customeraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addher_no', models.IntegerField(blank=True, max_length=12, null=True)),
                ('addher_name', models.CharField(blank=True, max_length=12, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customers')),
            ],
        ),
    ]
